config/routes.rb
AmericanLit400::Application.routes.draw do
  devise_for :admins

	resources :sub, :controller=>'subscribers', :only=>[:create]
	resources :site_infos
	resources :custom_urls

  match '/sub_save_pref', :to=>'subscribers#save_pref'
	match '/manage_urls', :to=>'admins#manage_urls', :as => :manage_urls
	match '/manage_subs', :to=>'admins#manage_subs',:as => :manage_subs
	match '/manage_site_infos', :to=>'site_infos#index',:as => :manage_site_infos
	match '/admin', :to=>'admins#manage_subs'
	match '/dashboard', :to=>'admins#manage_subs'
  match '/success', :to=>'pages#success'

  match '/success_final', :to=>'pages#success_final'

	match '/:custom_url', :to=>'pages#redirections',:via=>'get'

  root :to => "pages#index"

end

app/views/pages/_carousel.html.erb
    <div id="myCarousel" class="carousel">
    <!-- Carousel items -->
    <div class="carousel-inner">
    <div class="active item">
    <%= image_tag '1.jpg',:style=>'height:550px'%>
    </div>
    <div class="item">
    <%= image_tag '2.jpg',:style=>'height:550px'%>
    </div>
    <div class="item">
    <%= image_tag '3.jpg',:style=>'height:550px'%>
    </div>
    <div class="item">
    <%= image_tag '4.jpg',:style=>'height:550px' %>
    </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>

app/views/pages/_custom_css.html.erb
<style>
  body {
    background-color:white;
    background-image: url('http://emm-a-man.com/emmaman/wp-content/uploads/2012/04/DSC_1908.jpg');
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }
  .hero-unit {
    background-color:black;
    color:white;
    opacity:0.8;
    filter:alpha(opacity=80); /* For IE8 and earlier */
    width: 280px;
    padding: 50px;
    margin: 0;
  }
  img {
    height: 550px;
  }
  .item img{
    height: 550px;
  }
  .row-fluid{
    height: 550px;
  }
</style>
        <!--<ul class="cb-slideshow">
            <li><span>Image 01</span><div><h3>re·lax·a·tion</h3></div></li>
            <li><span>Image 02</span><div><h3>qui·e·tude</h3></div></li>
            <li><span>Image 03</span><div><h3>bal·ance</h3></div></li>
            <li><span>Image 04</span><div><h3>e·qua·nim·i·ty</h3></div></li>
            <li><span>Image 05</span><div><h3>com·po·sure</h3></div></li>
            <li><span>Image 06</span><div><h3>se·ren·i·ty</h3></div></li>
        </ul>-->

app/views/pages/_pref.html.haml
%h2 
  %font{:style=>'color:rgb(0,136,206)'}
    Check some categories 
  for a more relevant experience
%br
%br
= form_for :subscriber, :url => sub_save_pref_path,:remote=>true  do |f|
  = f.hidden_field :email, :value=>@subscriber.email
  %h2{:style=>'font-size:2em'}
    = f.check_box :shoes
    Shoes
  %h2{:style=>'font-size:2em'}
    = f.check_box :watches
    Watches
  %h2{:style=>'font-size:2em'}
    = f.check_box :casual
    Casual Wear
  %h2{:style=>'font-size:2em'}
    = f.check_box :formal_ties
    Formal Wear / Ties
  %h2{:style=>'font-size:2em'}
    = f.check_box :denim
    Denim
  %h2{:style=>'font-size:2em'}
    = f.check_box :sunglasses
    Summer Wear / Sunglasses
  %br
  %button{:id=>'subscribe_button', :class=>"btn btn-warning btn-large", :style=>'opacity:1.0;height:2.1em;font-size:2em;vertical-align:top;', :onclick=>"$().button('loading')"}
    save

app/views/pages/_referal_modal.html.haml
.modal{:id=>'myModal', :style=>'display:none'}
  .modal-header
    %button{:class=>'close', 'data-dismiss' => 'modal'} ×
    %h3 Invite Your Friends and Earn Purchase Credits!
  .modal-body
    Share this link and earn.
    %a{:href=>'#', :onclick=>"selectAll('referal-link')"} Select
    %br
    #referal-link
      = link_to "#{root_url}?referer=#{@subscriber.email}", "#{root_url}?referer=#{@subscriber.email}" 
    %br
    %table{:style=>'width:100%',:class=>'table'}
      %tr
        %td{:style=>'width:50%'}  
          // note you have to escape or delete '%' signs for twitter's comment field
          %a{:href=>"#", :onclick=>"#{twitter_str(@subscriber.email)}", :title=>"Click to share this post on Twitter"}
            = image_tag('shareontwitter.png',:style=>'width:50%;height:52%')
        %td
          %a{:href=>'#', :title=>'Share on Facebook', :onclick=>"#{facebook_str(@subscriber.email)}"}
            = image_tag 'shareonfb.png',:style=>'width:50%;height:52%'
    %table{:style=>'width:100%'}
      %tr
        %td{:style=>'width:50%'}
          %b Founding Member
        %td 
          %b Prime Time Player
      %tr
        %td 10 friends have joined. $30 credit.
        %td 50 friends have joined. Free standard shipping for 2 month.
      %tr
        %td 
          %b VIP Members
        %td 
          %b Bonus
      %tr
        %td 25 friends have joined. $30 more credit.
        %td $25 credit when friend makes first $25 purchase within 30 days of joining.
  .modal-footer

app/views/pages/_sign_up_form.html.erb
    <%= form_for "subscriber", :url => sub_index_path, :method=>'post',:remote=>true do |f| %>                                      
      <%= f.hidden_field :referer,:value=>@referer%>
      <div id='response' style="display:none;">
      </div>
		<div id="sub_form">
      <%= f.text_field :email, 
              :placeholder=>'vip@example.com', 
              :style=>'font-size:2em;height:2em;width:10em' %> 
      <button id='subscribe_button' 
            class="btn btn-warning btn-large" 
            style='opacity:1.0;height:2.1em;font-size:2em;vertical-align:top;' 
            onclick="$().button('loading')"
            data-loading-text='saving...'>
            Request Invite
      </button>
	</div>
    <% end %>
  We will never sell your information. Ever.
</div>

app/views/pages/_success_message.html.haml
%h2 Success!
%br
%h2 We will send you an invite as soon as spaces open up!
%br
%h2 
  In the mean time, you can earn 
  //= link_to 'purchase credits', "#{root_url}?referer=#{@subscriber.email}"
  = link_to 'credits for purchase', '#myModal', 'data-toggle'=>'modal' 
  by referring friends.
%br

app/views/pages/_successmessage.html.erb
<div id='success_message'><h1>Thank you for signing up! <br> We'll love to have you play around with our beta! </h1></div>

app/views/pages/about.html.erb
<%= render 'custom_header' %>
<div class="container">
      <div class="hero-unit" style="background-image:url(''); background-size:50%;background-repeat:no-repeat;background-position:right;filter:alpha(opacity=100);">
        <font color="#0065d0">
						<h1>The Team</h1>
				</font>
	
<table>
<tr>
<td>
					<h3>We are a passionate team of graduate students and industry veterans aimed to ease how monetization and commerce works with the rise of social networks and games.</h3><br>
</td>
<td>
            <div class="demo">
                <div id="capslide_img_cont12" class="ic_container">
		<img src="http://i1143.photobucket.com/albums/n639/indigio/trevor.jpg" alt="" width="125" height="125"/>
                    <div class="overlay" style="display:none;"></div>
                    <div class="ic_caption">
                        <p class="ic_category">Trevor</p>
                        <!--<h3>Amazing Image Title</h3>
                        <p class="ic_text">
                           Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        </p>-->
                    </div>
                </div>
            </div>
</td>
<td>
            <div class="demo">
                <div id="capslide_img_cont15" class="ic_container">
		<img src="http://i1143.photobucket.com/albums/n639/indigio/tom.jpg" alt="" width="125" height="125"/>
                    <div class="overlay" style="display:none;"></div>
                    <div class="ic_caption">
                        <p class="ic_category">Tom</p>
                        <!--<h3>Amazing Image Title</h3>
                        <p class="ic_text">
                           Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        </p>-->
                    </div>
                </div>
            </div>
</td>
<td>
            <div class="demo">
                <div id="capslide_img_cont16" class="ic_container">
		<img src="http://i1143.photobucket.com/albums/n639/indigio/alex.jpg" alt="" width="125" height="125"/>
                    <div class="overlay" style="display:none;"></div>
                    <div class="ic_caption">
                        <p class="ic_category">Han</p>
                        <!--<h3>Amazing Image Title</h3>
                        <p class="ic_text">
                           Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        </p>-->
                    </div>
                </div>
            </div>
</td>
</tr>
</table>
</div>
<br>
        <div class="span6">
<h1>Contact Us</h1>
				<hr>	
		<h3>Emails</h3>
<table style="">
	<tr>
		<tr>
		<td>Corporate Inquiries</td>
		<td>info@ingidio.com</td>
		</tr>
		<tr>
		<td>Press Inquiries</td>
		<td>pr@ingidio.com</td>
		</tr>
		<tr>
		<td>Job Inquiries</td>
		<td>jobs@ingidio.com</td>
		</tr>
		<tr>
		<td>Customer Support</td>
		<td>suppport@ingidio.com</td>
		</tr>
	</tr>
</table>			
<br>
			<h3>Address</h3>
<table>
		<tr>
			<td>
				Ingidio Technologies
			</td>
		</tr>
			<tr>
				<td>
					440 N. Wolfe Road
				</td>
			 </tr>
			<tr>
				<td>
					Sunnyvale, CA 94085
				</td>
			</tr>
</table>
</div>
<script src="/robot_js/jquery.capSlide.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function() {
                $("#capslide_img_cont12").capslide({
                    caption_color	: '#bfedfa',
                    caption_bgcolor	: '#000',
                    overlay_bgcolor : '#000',
                    border			: '4px solid #444',
                    showcaption	    : false
                });
                $("#capslide_img_cont13").capslide({
                    caption_color	: '#bfedfa',
                    caption_bgcolor	: '#000',
                    overlay_bgcolor : '#000',
                    border			: '4px solid #444',
                    showcaption	    : false
                });
                $("#capslide_img_cont14").capslide({
                    caption_color	: '#bfedfa',
                    caption_bgcolor	: '#000',
                    overlay_bgcolor : '#000',
                    border			: '4px solid #444',
                    showcaption	    : false
                });
                $("#capslide_img_cont15").capslide({
                    caption_color	: '#bfedfa',
                    caption_bgcolor	: '#000',
                    overlay_bgcolor : '#000',
                    border			: '4px solid #444',
                    showcaption	    : false
                });
                $("#capslide_img_cont16").capslide({
                    caption_color	: '#bfedfa',
                    caption_bgcolor	: '#000',
                    overlay_bgcolor : '#000',
                    border			: '4px solid #444',
                    showcaption	    : false
                });
                $("#capslide_img_cont17").capslide({
                    caption_color	: '#bfedfa',
                    caption_bgcolor	: '#000',
                    overlay_bgcolor : '#000',
                    border			: '4px solid #444',
                    showcaption	    : false
                });

            });
        </script>
</div>
<%= render 'custom_footer' %>

app/views/pages/contact.html.erb
    <%= render 'layouts/toolbar' %>
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Hi There! How Can We Help?</h1>
	<br>
	<p>Email us at <a href="#">Ingidio.tv@gmail.com</a> . We will respond as soon as we can. Promise!</p>
      </div>
	<%= render 'layouts/footer' %>
    </div> <!-- /container -->

app/views/pages/index1.html.erb
    <%= form_for "subscriber", :url => sub_index_path, :method=>'post',:remote=>true do |f| %>                                      
      <div id='response' style="display:none;width:40.5em">
      </div>
		<div id="sub_form">
      <%= f.text_field :email, :placeholder=>'test@example.com', :style=>'font-size:2em;height:2em;width:15em' %> 
      <button id='subscribe_button' class="btn btn-primary btn-large" 
					style='opacity:1.0;height:2.4em;font-size:2em;vertical-align:top;' 
          onclick="$(this).button('loading')" data-loading-text='saving...'>
            Request Invite
      </button>
	</div>
    <% end %>
  </p>
	Only jerks spam you and jerks we are not.
</div>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/pages/success.html.haml
= render 'custom_css'
.row-responsive
  .span6
    .hero-unit
      =render 'pages/success_message'
  .span6{:id=>'page-right',:style=>'float:right'}
    .hero-unit
      = render 'pages/pref'

app/views/pages/success_final.html.haml
= render 'custom_css'
.row-responsive
  .span6
    .hero-unit
      =render 'pages/success_message'
  .span6{:id=>'page-right',:style=>'float:right'}
    .hero-unit
      = render 'pages/pref_saved'