config/routes.rb
AmericanLit400::Application.routes.draw do
  devise_for :admins

	resources :sub, :controller=>'subscribers', :only=>[:create]
	resources :site_infos
	resources :custom_urls

  match '/sub_save_pref', :to=>'subscribers#save_pref'
	match '/manage_urls', :to=>'admins#manage_urls', :as => :manage_urls
	match '/manage_subs', :to=>'admins#manage_subs',:as => :manage_subs
	match '/manage_site_infos', :to=>'site_infos#index',:as => :manage_site_infos
	match '/admin', :to=>'admins#manage_subs'
	match '/dashboard', :to=>'admins#manage_subs'
  match '/success', :to=>'pages#success'

  match '/success_final', :to=>'pages#success_final'

	match '/:custom_url', :to=>'pages#redirections',:via=>'get'

  root :to => "pages#index"

end

app/models/custom_url.rb
class CustomUrl < ActiveRecord::Base
	attr_accessible :end_point, :url
end

# == Schema Information
#
# Table name: custom_urls
#
#  id         :integer(4)      not null, primary key
#  end_point  :string(255)
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/custom_urls_controller.rb
class CustomUrlsController < ApplicationController
  def new
		@custom_url = CustomUrl.new
  end

	def create
		@url = validate_redirect_url(params[:custom_urls][:url])
		params[:custom_urls][:url] = @url
		puts @url
		@custom_url = CustomUrl.new(params[:custom_urls])


		if @custom_url.save
			redirect_to custom_urls_path
		else 
			redirect_to new_custom_url_path
		end
	end

	def update
	end

	def index
		@manage_urls = 'active'
		@title = 'Manage URLs'
		@c_urls = CustomUrl.all
		@custom_url = CustomUrl.new
	end

	def show
	end

	def destroy
		@custom_url = CustomUrl.find(params[:id])
		@custom_url.delete
		redirect_to custom_urls_path
	end

	def validate_redirect_url(str)
		if str[0..6] == 'http://' or str[0..7] == 'https://'
			return str
		else
			return 'http://' + str
		end
	end
end

app/helpers/custom_urls_helper.rb
module CustomUrlsHelper
end

app/views/custom_urls/index.html.erb
<table style="width:100%">
<tr>
	<td>
	<h3>End Point</h3>
	</td>
	<td>
	<h3>Redirect URL</h3>
	</td>
	<td>
	</td>
<tr>
<% @c_urls.each do |c_url| %>
	<tr>
		<td>
		<%= link_to c_url.end_point, c_url.end_point %>
		</td>
		<td>
		<%= link_to c_url.url, c_url.url %>
		</td>
		<td>
		<%= link_to "delete", custom_url_path(c_url.id), :method=>'delete',:class=>'btn' %>
		</td>
	</tr>
<% end %>
</table>

<br>
<br>
<br>
<br>
<br>
<br>
<!--<p>
<%= link_to "Add a link pair", new_custom_url_path,:class=>"btn btn-primary btn-large" %>
</p>-->

<div class="well">
<table style="width:100%">
<%= form_for "custom_urls",:url=>{:controller=>'custom_urls', :action=>'create'},:method=>'post' do |f|%>
	<tr>
	<td>
	<h3>
		URL End Point 
	</h3>
	(ie. 'manga' for ingidio/managa, 'food' for ingidio/food)
	</td>
	<td>
	<h3>
		External URL 
	</h3>
		(ie. URL you are linking to. Ends with .net, .com or whatever)
	</td>
	<td>
	</td>
	</tr>
	<tr>
	<td>
	<%= f.text_field :end_point,:placeholder=>'example' %>
	</td>
	<td>
	<%= f.text_field :url,:placeholder=>'example.com' %>
	</td>
	<td>
	<button class='btn btn-large btn-primary' type='submit'>
		Add Link
	</button>
	</td>
	</tr>
<% end %>
</table>
</div>

app/views/custom_urls/new.html.erb
<%= form_for "custom_urls",:url=>{:controller=>'custom_urls', :action=>'create'},:method=>'post' do |f|%>

	<h3>URL End Point (ie. 'manga' for ingidio/managa, 'food' for ingidio/food)</h3>
	<%= f.text_field :end_point,:placeholder=>'example' %>
	<br>
	<h3>External URL (ie. URL you are linking to. Ends with .net, .com or whatever)</h3>
	<%= f.text_field :url,:placeholder=>'example.com' %>
	<br>
	<%= f.submit, :class=>'btn btn-large btn-primary' %>
	<button class='btn btn-large btn-primary' type='submit'>
		Add Link
	</button>
<% end %>