config/routes.rb
AmericanLit400::Application.routes.draw do
  devise_for :admins

	resources :sub, :controller=>'subscribers', :only=>[:create]
	resources :site_infos
	resources :custom_urls

  match '/sub_save_pref', :to=>'subscribers#save_pref'
	match '/manage_urls', :to=>'admins#manage_urls', :as => :manage_urls
	match '/manage_subs', :to=>'admins#manage_subs',:as => :manage_subs
	match '/manage_site_infos', :to=>'site_infos#index',:as => :manage_site_infos
	match '/admin', :to=>'admins#manage_subs'
	match '/dashboard', :to=>'admins#manage_subs'
  match '/success', :to=>'pages#success'

  match '/success_final', :to=>'pages#success_final'

	match '/:custom_url', :to=>'pages#redirections',:via=>'get'

  root :to => "pages#index"

end

app/views/layouts/_footer.html.erb
      <!--<footer>
        <p>&copy; 2012</p>
      </footer>-->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">bossary</a>

				<ul class="nav">
					<% if current_admin %>
						<li class="<%= @home %>"><a href="/">Home</a></li>
						<li class="<%= @manage_urls %>">
							<%= link_to "Sub-URLs", manage_urls_path %>
						</li>

						<li class="<%= @manage_subs %>">
							<%= link_to "Subscribers", manage_subs_path %>
						</li>
						<li class="<%= @manage_site_infos %>">
							<%= link_to "Site Infos", manage_site_infos_path %>
						</li>
						<li><%= link_to "Logout", destroy_admin_session_path,:method=>'delete' %></li>
					<% end %>
				</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Bossary | <%= @title %></title>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'bootstrap-button','bootstrap-modal' %>
  <%= csrf_meta_tag %>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="<%= SiteInfo.first.meta_data %>">
	<meta name="author" content="">

    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
		
</head>
<body>
<% if current_admin %>
<%= render "layouts/header" %>
<% end %>

<%= yield %>

<%= render "layouts/footer" %>
<!--<%= debug(params) if Rails.env.development? %>-->
<!-- google analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31569191-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>